spring:
    application:
        name: shiptime-integration-backend
    config:
        import: "file:./backend/src/main/resources/.env[.properties]"
    profiles:
        active: ${SRC_PROFILE:default}

server:
    port: ${SRC_PORT:9000}

logging:
    threshold:
        console: WARN
        file: TRACE
    file:
        name: ${spring.application.name}_${APP_PROFILE:default}.log

client:
    logging:
        include-headers: false
        enabled: true
        truncate-logs: true
        single-line: true

---

spring:
    config:
        activate:
            on-profile: devlocal

shiptime:
    base-url: http://localhost:8080

---
spring:
    config:
        activate:
            on-profile: "!devlocal"

shiptime:
    base-url: https://sandboxrestapi.shiptime.com
    auth:
        username: ${SHIPTIME_USERNAME}
        password: ${SHIPTIME_PASSWORD}
